let stock = [
	{id: 1, nombre: "vogue" , tipo: "remera" , precio: 1299, cantidad: 4,  talle: "S", img: "./img/foto10.png"},
	{id: 2, nombre: "vogue" , tipo: "remera" , precio: 1299, cantidad: 4,  talle: "M"  , img: "./img/foto18.png"},
	{id: 3, nombre: "vogue" , tipo: "remera" , precio: 1299,  cantidad: 4, talle: "L" ,img: "./img/foto8.png"},
	{id: 4, nombre: "vogue" , tipo: "remera" , precio: 1299,  cantidad: 4, talle: "XL" ,img: "./img/foto9.png"},
	{id: 5, nombre: "colores" , tipo: "remera" , precio: 1299, cantidad: 4,  talle: "S" ,img: "./img/foto7.png"},
	{id: 6, nombre: "colores" , tipo: "remera" , precio: 1299,  cantidad: 4, talle: "M" ,img: "./img/foto3.png"},
	{id: 7, nombre: "colores" , tipo: "remera" , precio: 1299, cantidad: 4,  talle: "L" ,img: "./img/foto2.png"},
	{id: 8, nombre: "colores" , tipo: "remera" , precio: 1299, cantidad: 4,  talle: "XL" ,img: "./img/foto1.png"},
	{id: 9, nombre: "ACDC" , tipo: "remera" , precio: 1499,  cantidad: 4, talle: "S" ,img: "./img/foto11.png"},
	{id: 10, nombre: "ACDC" , tipo: "remera" , precio: 1499, cantidad: 4,  talle: "M" ,img: "./img/foto4.png"},
	{id: 11, nombre: "ACDC" , tipo: "remera" , precio: 1499,  cantidad:5 , talle: "L" ,img: "./img/foto5.png"},
	{id: 12, nombre: "ACDC" , tipo: "remera" , precio: 1499, cantidad:5 ,  talle: "XL" ,img: "./img/foto8.png"},
	{id: 13, nombre: "rose" , tipo: "remera" , precio: 1099,  cantidad:5 , talle: "S" ,img: "./img/foto8.png"},
	{id: 14, nombre: "rose" , tipo: "remera" , precio: 1099,  cantidad:5 , talle: "M" ,img: "./img/foto8.png"},
	{id: 15, nombre: "rose" , tipo: "remera" , precio: 1099, cantidad:5 ,  talle: "L" ,img: "./img/foto8.png"},
	{id: 16, nombre: "rose" , tipo: "remera" , precio: 1099,  cantidad:5 , talle: "XL" ,img: "./img/foto8.png"},
	{id: 17, nombre: "body gris" , tipo: "body" , precio: 999, cantidad:5 ,  talle: "U" ,img: "./img/foto8.png"},
	{id: 18, nombre: "body crema" , tipo: "body" , precio: 999,  cantidad:5 , talle: "U" ,img: "./img/foto8.png"},
	{id: 19, nombre: "body naranja" , tipo: "body" , precio: 999,  cantidad:5 , talle: "U" ,img: "./img/foto8.png"},
	{id: 20, nombre: "top celeste" , tipo: "top" , precio: 999,  cantidad:5 , talle: "U" ,img: "./img/foto8.png"},
	{id: 21, nombre: "top celeste" , tipo: "top" , precio: 999,  cantidad:5 , talle: "U" ,img: "./img/foto8.png"},
	{id: 22, nombre: "top pasion" , tipo: "top" , precio: 999,  cantidad:5 , talle: "U" ,img: "./img/foto8.png"},
	{id: 23, nombre: "top pasion" , tipo: "top" , precio: 999,  cantidad:5 , talle: "U" ,img: "./img/foto8.png"},
]